add_newline = false
scan_timeout = 10
command_timeout = 1000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$character\
$jobs\
$status\
$shlvl\
$shell\
[ ](#475062)\
"""

[character]
disabled = true
success_symbol = "[晴](#A3BE8C)"
error_symbol = "[塚](#BF616A)"
vicmd_symbol = "[](#88C0D0)"

[directory]
home_symbol = ""

[shell]
disabled = true

